services:
  db:
    image: mysql:8.4.0
    volumes:
      - ./db/initdb.d/:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
  redis:
    image: redis
    ports:
      - "6379:6379"
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "1323:1323"
    depends_on:
      - redis
      - db

